# Generated by Django 4.0.7 on 2022-09-23 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorservices',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.doctors'),
        ),
        migrations.AddField(
            model_name='doctorservices',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.services'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='doctor_time_slots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctortimeslots'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.patients'),
        ),
    ]
