# Generated by Django 4.0.5 on 2022-06-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='booking_code',
        ),
    ]
