# Generated by Django 4.0.5 on 2022-06-23 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('hospital', '0004_alter_doctortimeslots_doctor_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='doctor_time_slots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctortimeslots'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.patients'),
        ),
        migrations.AlterField(
            model_name='doctorservices',
            name='doctor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctors'),
        ),
        migrations.AlterField(
            model_name='doctorservices',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.services'),
        ),
        migrations.AlterField(
            model_name='doctortimeslots',
            name='doctor_service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctorservices'),
        ),
        migrations.AlterField(
            model_name='doctortimeslots',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctortimeslots',
            name='start_date',
            field=models.DateField(),
        ),
    ]
