# Generated by Django 4.0.5 on 2022-06-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_doctorservices_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='booking_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
