# Generated by Django 4.0.5 on 2022-06-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_appointments_booking_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='doctorservices',
            options={'verbose_name_plural': 'DoctorServices'},
        ),
        migrations.AlterModelOptions(
            name='doctortimeslots',
            options={'verbose_name_plural': 'DoctorTimeSlots'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
    ]
