# Generated by Django 4.0.5 on 2022-06-29 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_appointments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortimeslots',
            name='doctor_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctorservices'),
        ),
    ]
